version: 2.1
jobs:
  config_deploy_infra:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["e7:73:c6:34:99:04:15:02:87:e1:4a:d3:f1:92:7b:28"]
      - run:
          name: install dependencies
          command: |
            apk add --update --allow-untrusted ansible
      - run: export ANSIBLE_HOST_KEY_CHECKING=False
      - run:
          name: configure server
          command: |
            ansible-playbook  project/playbook.yml  -i project/inventory.txt
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test script
          command: |
            URL="54.188.65.146:3000"
            if curl -s --head ${URL}
            then
              return 0
            else
              return 1
            fi
workflows:
  myflow:
    jobs:
      - config_deploy_infra
      - smoke_test:
          requires:
            - config_deploy_infra
