version: 2.1
jobs:
  config_deploy_infra:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["b7:17:27:54:4e:b3:04:89:d0:29:a7:01:00:6a:12:e5"]
      - run:
          name: install dependencies
          command: |
            apk add --update --allow-untrusted ansible
      - run:
          name: configure server
          command: |
            ansible-playbook  project/playbook.yml  -i inventory.txt
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test script
          command: |
            URL="54.188.65.146:3000"
            if curl -s --head ${URL}
            then
              return 0
            else
              return 1
            fi
workflows:
  myflow:
    jobs:
      - config_deploy_infra
      - smoke_test:
          requires:
            - config_deploy_infra
